name: update ips
on:
  schedule:
    # every Thursday at 0:0
    - cron: "0 0 * * 4"
jobs:
  fetch-ip:
    runs-on: ubuntu-latest
    steps:
      - name: install dep
        run: sudo apt install iprange
      # Checkout the branch
      - name: checkout
        uses: actions/checkout@v2

      - name: update ip
        run: |
          ./update.sh

      - name: setup git config
        run: |
          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: commit
        run: |
          # Stage the file, commit and push
          git add cnip.txt
          git commit -m "ip update"
          git push origin main
